services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yolo123
      POSTGRES_DB: user_api
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:yolo123@postgres:5432/user_api?sslmode=disable
    ports:
      - "8080:8080"