version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: user-api-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_api

    ports:
      - "5432:5432"

  app:
    build: .

    container_name: user-api

    depends_on:
      - postgres

    ports:
      - "8080:8080"